version: '3'

services:
  robin_db:
    container_name: robindb
    image: postgres:13.3-alpine
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: robinhoodAseca
      POSTGRES_PASSWORD: robinhood
      POSTGRES_DB: robinhood
    volumes:
      - robin_data:/var/lib/postgresql/data

  robin_api:
    container_name: robinapi
    depends_on:
      - robin_db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USER: robinhoodAseca
      DB_PASSWORD: robinhood
      DB_NAME: robinhood
      DB_HOST: robin_db
      DB_PORT: 5432

volumes:
  robin_data: